baseURL = 'https://www.epsteinfacts.com'
languageCode = 'en-us'
title = 'The Epstein Files: Uncovering the Truth'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'github'
    tabWidth = 4

[params]
  description = 'A comprehensive resource for information and documents related to the Jeffrey Epstein case.'
  googleAnalytics = "G-TP1L00RTZP"
  favicon = 'favicon.ico'

[menu]


[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
